apiVersion: v1
kind: Secret
metadata:
  name: redcap-service-secrets
  namespace: ecrin
type: Opaque
stringData:
  # DEV SECRETS - Mock REDCap for local development
  # In production, use real REDCap credentials
  REDCAP_API_URL: 'http://mock-redcap:8080/api/'
  REDCAP_API_TOKEN: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
